### ISSUE TITLE
Deprecate Ember.String monkey patching and globals API

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember-inflector#125]
`Ember.String.singularize()` and `Ember.String.pluralize()`will not be supported in https://github.com/ember-cli/ember-rfc176-data and should be used by importing them from `ember-inflector`. We should retire the globals APIs in this project and move towards just using explicit imports to make tree shaking easier.

/cc @locks @rwjblue @cibernox

**Comment by stefanpenner** [comment]
👍

**Comment by locks** [comment]
I think this is closed by #131?
