### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by mickael-palma-argus** [emberjs/ember-inflector#134]
Hi,

I try something very basic :
```javascript
Ember.Inflector.inflector.pluralize('equipment')
"equipment"

Ember.Inflector.inflector.irregular('equipment', 'equipments')

Ember.Inflector.inflector.pluralize('equipment')
"equipment"
```

the rule does not apply, any tips ?

Thank you

**Comment by giano** [comment]
sam

**Comment by bekzod** [comment]
https://www.learnersdictionary.com/qa/equipments-equipment-noncount-mass-noun-singular-plural#:~:text=The%20noun%20equipment%20does%20not,is%20no%20word%20%22equipments.%22&text=Below%20are%2010%20other%20common%20noncount%20nouns%2C%20shown%20in%20typical%20contexts.
