### ISSUE TITLE
Hoofs vs Hooves

### ISSUE THREAD

**Issue by Caltor** [emberjs/ember-inflector#153]
pluralize gives the plural of "hoof" as "hoofs". Shouldn't this be "hooves"?

**Comment by gnclmorais** [comment]
> There is nothing else to remember than the fact that "hoof" is a noun that accepts two distinct plural spellings. Both "hooves" and "hoofs" are correct, due to different rules of plural formation in English. — _[source](https://www.grammar.com/hooves_vs._hoofs)_

**Comment by Caltor** [comment]
Well I never knew that!
