### ISSUE TITLE
Update pluralize type definition to account for count and options arguments

### ISSUE THREAD

**Issue by timjcook** [emberjs/ember-inflector#176]
**Issue:**
Currently the `pluralize` type definition only handles the case where a single argument is passed to the helper. As of [this addition](https://github.com/emberjs/ember-inflector/commit/0e50b8a093cc5fe0d0ad8ab4dbe9355ad13de84a#diff-bbc138342ad94d49ed7fa53b3ba4d27d) we can now pass in a count to inform the method what it should base it's choice to pluralize on, and an options hash that controls if the passed in count is interpolated into the string.

**Fix:**
We require an update to the type definition to account for the new functionality. Perhaps by overloading the definition. This example works for me.
```
export function pluralize(someString: string): string; // <-- existing
export function pluralize(count: number, someString: string, options?: { // <-- new
  withoutCount: boolean
}): string;
```

**Comment by timjcook** [comment]
Happy to PR that if it seems reasonable.

**Comment by gnclmorais** [comment]
Related: https://github.com/emberjs/ember-inflector/pull/298

**Comment by timjcook** [comment]
fixed in https://github.com/emberjs/ember-inflector/pull/298
