### ISSUE TITLE
Upgrade to Ember 3.14 and drop support for Node 8

### ISSUE THREAD

**Issue by dmzza** [emberjs/ember-inflector#234]
It sounds like there is a plan to release a version 4.0 in #155. Does that include running `ember-cli-update --to latest`? 

Also, since Node 8 is reaching end-of-life on December 31, 2019, it seems like a good time to drop support for that too, which would be a breaking change requiring a major version bump anyway. 

If nobody else was planning to do this, I'm happy to submit a PR.

**Comment by rwjblue** [comment]
Seems good to me

**Comment by gnclmorais** [comment]
Support for Node 8 was dropped at https://github.com/emberjs/ember-inflector/pull/299, I believe. 🎊
