### ISSUE TITLE
@ember/string is not a dependency

### ISSUE THREAD

**Issue by timiyay** [emberjs/ember-inflector#347]
This package imports `@ember/string`, but doesn't list it in its `package.json`:
https://github.com/emberjs/ember-inflector/blob/06d0d8b038878060ed1139afade8b0418366917f/addon/lib/system/inflector.js#L1

I'm investigating an issue with a Yarn workspaces monorepo we have for our Ember addons, and opened this issue to try and clarify whether `@ember/string` is expected to be available some other way, such as via `ember-source`.

Our use case is:

- we're incrementally upgrading our addons from Ember 3.20 to Ember 3.24
- some addons have a dev dependency on `ember-data`
- when `ember-data` is upgraded to `~3.24` for one addon, other addons that are still on `ember-data@3.20` start failing CI with an error `Uncaught Error: Could not find module @ember/string imported from 'ember-inflector/lib/system/inflector'`

**Comment by timiyay** [comment]
I'm still investigating exactly what's causing our issues, it may be a combination of issues related to Yarn workspaces hoisting, and the fact that `ember-data@3.24` adds `@ember/string` as a dependency.

**Comment by EWhite613** [comment]
@timiyay did you ever figure this out? I have a similar issue with my Yarn workspace

**Comment by timiyay** [comment]
@EWhite613 we did, though I'm struggling to find the history of how we did it. We have some notes, but I'm not sure they were the final fix. I'll add them here anyway, in case it helps.

The trigger for our problems was upgrading `ember-data` from `3.20` to `3.24` in our Ember addons. This seemed to be enough to cause builds to fail with `Uncaught Error: Could not find module @ember/string imported from ember-inflector/lib/system/inflector`.

This error would show up in the apps that consume these addons, when trying to build.

Our fix was to upgrade `ember-data` all in one push for all addons, which was easy enough since they were in 1 monorepo.

After that, we'd have to bump these addons _and_ `ember-data` in our apps at the same time.

That's the best I can recall of our story 😅

**Comment by elfin-sbreuers** [comment]
Ember 5 removed automatic import of `@ember/string`. Wouldn't it be necessary to add `@ember/string` now to the dev-dependencies of this project, since it is using features of this module? That would allow to use it in Ember 5 projects without needing to list `@ember/string` as dependency though it is not really used in the project itself.
