### ISSUE TITLE
No longer works with `moduleResolution: node` with TS

### ISSUE THREAD

**Issue by lfloyd117** [emberjs/ember-inflector#510]
We updated to the latest `ember-inflector` (5.0.1) from 4.0.3 and TS can no longer resolve the module, leading to errors for any imports from ember-inflector. 

Our `moduleResolution` is set to `node`. If I change it to `nodenext` or `bundler` it works for ember-inflector but that is not looking to be an option as it breaks resolution for multiple other packages. 
This does not seem to be tied to its conversion to a v2 addon as we use many other v2 addon packages with TS and do not have resolution issues.

**Comment by NullVoxPopuli** [comment]
`"moduleResolution": "node"` is not correct for ember projects -- the default tsconfig base, seen here: https://github.com/tsconfig/bases/blob/main/bases/ember.json#L13, uses `"bundler"`

From the docs:
> 'node10' (previously called 'node') for Node.js versions older than v10, which only support CommonJS require. You probably won’t need to use node10 in modern code.

https://www.typescriptlang.org/tsconfig/#moduleResolution.


We don't support Node 10 or older, so I'm going to close this issue. Lemme know if you have questions! <3
