### ISSUE TITLE
Add inflector generator

### ISSUE THREAD

**Issue by michaelrkn** [emberjs/ember-inflector#92]
Currently, if a user wants to add a rule to the inflector, they have no guidance about where to do so. As a result, some people put their rules in the corresponding models, others in an initializer, and only [@rwjblue does it correctly](https://github.com/emberjs/guides/pull/899#issuecomment-149340100).

We're [adding documentation to the Guides encouraging @rwjblue's approach](https://github.com/emberjs/guides/pull/899), but ideally there would be a generator that would set things up along these lines:

``` js
// in app/app.js

// sets up Ember.Inflector
import './models/custom-inflector-rules';
```

``` js
// in app/models/custom-inflector-rules.js
var inflector = Ember.Inflector.inflector;
inflector.irregular('formula', 'formulae');
inflector.uncountable('advice');
```

**Comment by corrspt** [comment]
Hi,

I did try the solution proposed in that PR you linked to, but it didn't work for me. 

In issue #91 I had to add a serializer in addition to the initializer so that everything would work. Any thoughts on that situation?

Also, would that "custom-inflector-rules.js" only need to export the `inflector` variable to work?

**Comment by corrspt** [comment]
I maybe doing something else wrong, but if I remove my initializer and my serializer and just add your suggestion like this:

```js 
// app.js
import Ember from 'ember';
import Resolver from 'ember/resolver';
import loadInitializers from 'ember/load-initializers';
import config from './config/environment';
import './models/custom-inflector-rules';

let App;

Ember.MODEL_FACTORY_INJECTIONS = true;

App = Ember.Application.extend({
  modulePrefix: config.modulePrefix,
  podModulePrefix: config.podModulePrefix,
  Resolver
});

loadInitializers(App, config.modulePrefix);

export default App;

```

And 
```js
// models/custom-inflector-rules.js
var inflector = Ember.Inflector.inflector;
inflector.plural(/^gas$/, 'gases');
inflector.singular(/^gases$/, 'gas');
```

Then the request is made to `/get/gas` instead of `/gas/gases`

**Comment by fsmanuel** [comment]
what about
```
inflector.irregular('gas', 'gases');
```
instead of
```
inflector.plural(/^gas$/, 'gases');
inflector.singular(/^gases$/, 'gas');
```

**Comment by corrspt** [comment]
@fsmanuel  Same result.

I tried a console.log on that file (custom-inflector-rules) and it's being executed. 
If I console.log(inflector) in that file I get:

```
ember$inflector$lib$lib$system$inflector$$Inflector {rules: Object, _cacheUsed: false, _sCache: Object, _pCache: Object}
```
And this object inside the "rules" property does have the "gases" in the irregular property
![gas](https://cloud.githubusercontent.com/assets/789263/10690083/697d820a-7977-11e5-95a2-35c70f8a25c8.png)

But when the page is loaded if I got the console and do ´Ember.Inflector.inflector' I get this:
![gas2](https://cloud.githubusercontent.com/assets/789263/10690104/9a2b0a12-7977-11e5-8ad2-a92c27703c03.png)

Which doesn't have the property I added

**Comment by michaelrkn** [comment]
@corrspt did you manage to get it working?

@fsmanuel `ember g inflections` sounds good to me. As for the default blueprint, maybe @stefanpenner or @rwjblue has an opinion on the matter?

**Comment by corrspt** [comment]
@michaelrkn, with the help of @fsmanuel we found out that apparently there's a problem with [ember data](https://github.com/emberjs/data/issues/3881).

I've only managed to solve my problem by using a combination of initializer and serializer as I stated in issue #91.

**Comment by fsmanuel** [comment]
@michaelrkn I guess we don't need the default blueprint.
