### ISSUE TITLE
makeBoundHelper deprecated

### ISSUE THREAD

**Issue by Kallin** [emberjs/ember-inflector#93]
```
DEPRECATION: Using `Ember.HTMLBars.makeBoundHelper` is deprecated. Please refactor to using `Ember.Helper` or `Ember.Helper.helper`. [deprecation id: ember-htmlbars.make-bound-helper]
```

I'm seeing this deprecation warning that looks like it's coming from https://github.com/stefanpenner/ember-inflector/blob/bdb4165206c9fea9b27b3bb961d9b4885cee1a6c/addon/lib/utils/make-helper.js .

I'm not actually using inflector directly, but it's being pulled in from ember-data.

**Comment by fivetanley** [comment]
What version of Ember Data are you using? I think this should be fixed.
